import HocLayout from "./HocLayout";
import "./globals.scss";
import 'react-photo-view/dist/react-photo-view.css';

export const metadata = {
  title: "Jarvis Al Baasith",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <HocLayout>{children}</HocLayout>;
}
